version: '3.7'

services:

#######################################################################################################
  
  
  mysql_container:
    image: mysql:8.0.33
    container_name: mysql_container

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD : yes
      MYSQL_DATABASE: Mydatabase

    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
